create table accounts
(
    id       integer generated by default as identity
        constraint accounts_pkey
            primary key,
    active   boolean not null,
    username varchar(255)
);

create table students
(
    id         integer generated by default as identity
        constraint students_pkey
            primary key,
    age        integer not null,
    city       varchar(255),
    name       varchar(255),
    account_id integer
        constraint fksd9hvvjnstr8is6vhbv4dun1m
            references accounts
);

create table books
(
    id              integer generated by default as identity
        constraint books_pkey
            primary key,
    name            varchar(255),
    publishinghouse varchar(255)
);

create table accounts_books
(
    account_id integer not null
        constraint fkdpfsh6ldrgqnr82awscs2xrgw
            references accounts,
    books_id   integer not null
        constraint uk_eaolfd59bg064grduf5unsnty
            unique
        constraint fkhd84motbls2ee1w2urd97egix
            references books
);