create table base
(
    id          integer generated by default as identity
        constraint base_pkey
            primary key,
    description varchar(255)
);

create table vacancy
(
    id          integer generated by default as identity
        constraint vacancy_pkey
            primary key,
    description varchar(255)
);

create table base_vacancy
(
    base_id      integer not null
        constraint fklo2rl6sbnty82ukxbhb3qs5mo
            references base,
    vacancies_id integer not null
        constraint uk_fhbiaasp1fjf6iubjs00pxyfr
            unique
        constraint fkndmw003ws2cx544ynwr76yo7s
            references vacancy
);

create table candidate
(
    id         integer generated by default as identity
        constraint candidate_pkey
            primary key,
    experience integer          not null,
    name       varchar(255),
    salary     double precision not null,
    base_id    integer
        constraint fk6muim4wgwj68830na3fld06oa
            references base
);